name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  DJANGO_SETTINGS_MODULE: blog.settings.development
  DEV_DB_NAME: test_db
  DEV_DB_USER: test_user
  DEV_DB_PASSWORD: test_password
  DEV_DB_HOST: 127.0.0.1
  DEV_DB_PORT: 5432
  DEV_DEBUG: 'True'
  DEV_ALLOWED_HOSTS: localhost
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SECRET_KEY:  ${{ secrets.SECRET_KEY }}

jobs:
  test-and-analyze:
    name: Test and Analyze
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd "pg_isready -U test_user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h $DEV_DB_HOST -p $DEV_DB_PORT; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Run makemigrations
        run: |
          python manage.py makemigrations userprofile tags articles categories resources user_preferences,
      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests and generate coverage report
        run: |
          coverage run --rcfile=.coveragerc manage.py test
          coverage xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=PluraNex_blog-api
            -Dsonar.organization=pluranex
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.qualitygate.wait=true


  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: test-and-analyze
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to Dev Server
        run: |
          echo "Deploying to development server..."
          # Adicione comandos de deploy para o seu ambiente de desenvolvimento aqui

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test-and-analyze
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Deploy to Prod Server
        run: |
          echo "Deploying to production server..."
          # Adicione comandos de deploy para o seu ambiente de produção aqui
